#!/usr/bin/env bash
# =============================================================================
# generate_peer.sh — Mint a new WireGuard peer keypair + config
# =============================================================================
# USAGE
#   sudo bash generate_peer.sh <peer-name> <vpn-ip> <allowed-ips> [comment]
#
# EXAMPLE
#   sudo bash generate_peer.sh contractor2 10.0.0.5 "10.0.0.0/24,10.10.1.0/24" \
#     "Second contractor — Dev segment only"
#
# OUTPUT
#   /etc/wireguard/keys/<peer-name>.key   (chmod 0600)
#   /etc/wireguard/keys/<peer-name>.pub
#   /etc/wireguard/peer-configs/<peer-name>.conf
#   Appends [Peer] block to /etc/wireguard/wg0.conf
# =============================================================================

set -euo pipefail

PEER_NAME="${1:-}"
PEER_VPN_IP="${2:-}"
ALLOWED_IPS="${3:-}"
COMMENT="${4:-New peer}"

[[ -z "$PEER_NAME" || -z "$PEER_VPN_IP" || -z "$ALLOWED_IPS" ]] && {
  echo "Usage: $0 <name> <vpn-ip> <allowed-ips> [comment]"
  exit 1
}
[[ $EUID -eq 0 ]] || { echo "Run as root"; exit 1; }

WG_DIR="/etc/wireguard"
KEY_DIR="${WG_DIR}/keys"
PEER_DIR="${WG_DIR}/peer-configs"
SERVER_CONF="${WG_DIR}/wg0.conf"
WG_PORT=51820

install -d -m 0700 "$KEY_DIR"
mkdir -p "$PEER_DIR"

PRIV="${KEY_DIR}/${PEER_NAME}.key"
PUB="${KEY_DIR}/${PEER_NAME}.pub"

echo "[+] Generating keypair for: $PEER_NAME"
wg genkey | install -m 0600 /dev/stdin "$PRIV"
wg pubkey < "$PRIV" > "$PUB"
chmod 0644 "$PUB"

SERVER_PUB=$(cat "${KEY_DIR}/server.pub")
PEER_PRIV=$(cat "$PRIV")
GATEWAY_IP=$(curl -s --max-time 5 ifconfig.me || ip route get 1.1.1.1 | awk '{print $7; exit}')

cat > "${PEER_DIR}/${PEER_NAME}.conf" <<EOF
# Generated by generate_peer.sh — $(date)
# Peer: ${PEER_NAME} | Role: ${COMMENT}

[Interface]
PrivateKey = ${PEER_PRIV}
Address    = ${PEER_VPN_IP}/32

[Peer]
PublicKey           = ${SERVER_PUB}
Endpoint            = ${GATEWAY_IP}:${WG_PORT}
AllowedIPs          = ${ALLOWED_IPS}
PersistentKeepalive = 25
EOF

echo "[+] Peer config: ${PEER_DIR}/${PEER_NAME}.conf"

# Add to server config
cat >> "$SERVER_CONF" <<EOF

# Peer: ${PEER_NAME} — ${COMMENT}
[Peer]
PublicKey  = $(cat "$PUB")
AllowedIPs = ${PEER_VPN_IP}/32
EOF

echo "[+] Added to server config: ${SERVER_CONF}"
echo "[+] Reloading WireGuard…"
wg syncconf wg0 <(wg-quick strip wg0)
echo "[+] Done. Distribute ${PEER_DIR}/${PEER_NAME}.conf to the peer."
echo ""
echo "⚠  Remember to add firewall rules in /etc/nftables.conf for this peer's"
echo "   segment access before distributing the config (nftables = LAYER 2)."
